$baseDir = "c:\Users\ariol\.gemini\yatchbooking\azur-yachts\src"
$dirs = @(
    "app/(public)/listing/[id]",
    "app/(public)/contact",
    "app/(public)/about",
    "app/(public)/faq",
    "app/(public)/legal",
    "app/(auth)/login",
    "app/(auth)/register",
    "app/(auth)/reset-password",
    "app/(protected)/dashboard/listings/new",
    "app/(protected)/dashboard/bookings",
    "app/(protected)/dashboard/messages",
    "app/(protected)/verify",
    "app/(protected)/profile",
    "app/(protected)/bookings/[id]/payment",
    "app/(protected)/favorites",
    "app/(admin)/admin/users",
    "app/(admin)/admin/listings",
    "app/(admin)/admin/bookings",
    "app/(admin)/admin/payments",
    "app/(admin)/admin/messages",
    "app/(admin)/admin/pages",
    "app/(admin)/admin/faq",
    "app/(admin)/admin/settings/payments",
    "app/api/auth/[...nextauth]",
    "app/api/listings/[id]",
    "app/api/bookings/[id]",
    "app/api/payments/stripe/create-intent",
    "app/api/payments/stripe/webhook",
    "app/api/payments/paypal/create-order",
    "app/api/payments/paypal/capture",
    "app/api/payments/bank-transfer/submit-proof",
    "app/api/payments/bank-transfer/notify",
    "app/api/users/[id]",
    "app/api/reviews",
    "app/api/messages",
    "app/api/conversations",
    "app/api/notifications",
    "app/api/favorites",
    "app/api/upload",
    "app/api/pages",
    "app/api/faq",
    "app/api/cron/payment-reminders",
    "components/layout",
    "components/ui",
    "components/forms",
    "components/listing",
    "components/booking",
    "components/payment",
    "components/chat",
    "components/admin",
    "components/shared",
    "lib",
    "hooks",
    "store",
    "types"
)

foreach ($dir in $dirs) {
    if (-not (Test-Path "$baseDir\$dir")) {
        New-Item -ItemType Directory -Force -Path "$baseDir\$dir" | Out-Null
    }
}

$files = @(
    "app/(public)/page.tsx",
    "app/(public)/listing/page.tsx",
    "app/(public)/listing/[id]/page.tsx",
    "app/(public)/contact/page.tsx",
    "app/(public)/about/page.tsx",
    "app/(public)/faq/page.tsx",
    "app/(public)/legal/page.tsx",
    "app/(auth)/login/page.tsx",
    "app/(auth)/register/page.tsx",
    "app/(auth)/reset-password/page.tsx",
    "app/(protected)/dashboard/page.tsx",
    "app/(protected)/dashboard/listings/page.tsx",
    "app/(protected)/dashboard/listings/new/page.tsx",
    "app/(protected)/dashboard/bookings/page.tsx",
    "app/(protected)/dashboard/messages/page.tsx",
    "app/(protected)/verify/page.tsx",
    "app/(protected)/profile/page.tsx",
    "app/(protected)/bookings/[id]/page.tsx",
    "app/(protected)/bookings/[id]/payment/page.tsx",
    "app/(protected)/favorites/page.tsx",
    "app/(admin)/admin/page.tsx",
    "app/(admin)/admin/users/page.tsx",
    "app/(admin)/admin/listings/page.tsx",
    "app/(admin)/admin/bookings/page.tsx",
    "app/(admin)/admin/payments/page.tsx",
    "app/(admin)/admin/messages/page.tsx",
    "app/(admin)/admin/pages/page.tsx",
    "app/(admin)/admin/faq/page.tsx",
    "app/(admin)/admin/settings/payments/page.tsx",
    "app/api/auth/[...nextauth]/route.ts",
    "app/api/listings/route.ts",
    "app/api/listings/[id]/route.ts",
    "app/api/bookings/route.ts",
    "app/api/bookings/[id]/route.ts",
    "app/api/payments/stripe/create-intent/route.ts",
    "app/api/payments/stripe/webhook/route.ts",
    "app/api/payments/paypal/create-order/route.ts",
    "app/api/payments/paypal/capture/route.ts",
    "app/api/payments/bank-transfer/submit-proof/route.ts",
    "app/api/payments/bank-transfer/notify/route.ts",
    "app/api/users/route.ts",
    "app/api/users/[id]/route.ts",
    "app/api/reviews/route.ts",
    "app/api/messages/route.ts",
    "app/api/conversations/route.ts",
    "app/api/notifications/route.ts",
    "app/api/favorites/route.ts",
    "app/api/upload/route.ts",
    "app/api/pages/route.ts",
    "app/api/faq/route.ts",
    "app/api/cron/payment-reminders/route.ts",
    "app/layout.tsx",
    "app/globals.css",
    "lib/prisma.ts",
    "lib/auth.ts",
    "lib/cloudinary.ts",
    "lib/resend.ts",
    "lib/stripe.ts",
    "lib/socket.ts",
    "lib/utils.ts"
)

foreach ($file in $files) {
    if (-not (Test-Path "$baseDir\$file")) {
        New-Item -ItemType File -Force -Path "$baseDir\$file" | Out-Null
    }
}
Write-Host "Structure created successfully!"
